---
title: "Investigating performance in rising rate environments"
output: html_notebook
---

####Importing the data into R

```{r, message=FALSE}
#remove past data
rm(list = ls(envir = globalenv()),envir = globalenv()) #clear Vars from global enviroment

#load required packages
library(PerformanceAnalytics)
library(quantstrat)

#declare symbols
symbols <- c("TBILLS","SP500","EAFE","US10YR","GSCI","NAREIT","CPI")

#use quantmod function to load data as xts objects
getSymbols(symbols,
           src = "csv",
           dir="../Data/CSV files",
           col.names=c("Close"))
```


#### Calculating asset class returns and replicating the chart in Faber's Figure 3

```{r}
SubsetPeriod <- "1972-12-31::1981-09-30"

#combine all closing prices into one xts file
AllAssets <- cbind.xts(Cl(TBILLS),
                       Cl(SP500),
                       Cl(EAFE),
                       Cl(US10YR),
                       Cl(GSCI),
                       Cl(NAREIT),
                       Cl(CPI))                       

#subset to required period
AllAssets <- AllAssets[SubsetPeriod]
colnames(AllAssets) <- symbols

#calculate returns and cum returns
AllAssets.ret <- Return.calculate(AllAssets)[-1,]
AllAssets.cumret <- 100*cumprod(1+ ROC(AllAssets, type = "discrete")[-1,])

#chart returns
chart.TimeSeries(AllAssets.cumret[SubsetPeriod],
  main = paste("Figure 1 - Asset Class Returns ",substr(SubsetPeriod,1,4),"-",substr(SubsetPeriod,13,16),", Log Scale",sep = ""), 
  #lty = "2",
  ylab = "",
  ylog = TRUE,
  #ylim = c(40,6000),
  date.format = "%Y",
  major.ticks = "years",
  legend.loc = "topleft",
  colorset = c("orangered3","olivedrab","slateblue","blue","gold2","dodgerblue2","cornflowerblue"), #create own colorset at some point
  minor.ticks =FALSE)
```

####Analysing asset class returns, max drawdowns and other performance statistics

```{r}
#Create xts for Returns
Returns <- AllAssets.ret[SubsetPeriod]

#calculate statistics and store as "stats"
stats <- rbind(100*Return.annualized(Returns,scale = 12), 
               100*StdDev.annualized(Returns,scale = 12), 
               SharpeRatio.annualized(Returns,Rf = AllAssets.ret$TBILLS),
               100*maxDrawdown(Returns,scale = 12,invert = FALSE),
               100*c(Return.annualized(Returns$CPI,scale = 12)))

#rename table rows/column names and format
colnames(stats) <- symbols
rownames(stats) <- c("Return","Volatility",paste("Sharpe (",round(stats[1,"TBILLS"],2),"%)", sep = ""),"MaxDD","Inflation CAGR")
stats <- round(stats[,-7],2)

#Lets print the stats:
stats

#copies stats to clipboad for pasting into word/excel
write.table(stats, "clipboard", sep="\t", col.names=NA) 
```

###Now lets look at GTAA

```{r}
#Import saved pricing data csv files as xts
getSymbols("TBILLYIELDS",
           src = "csv",
           dir="../Data/CSV files",
           col.names=c("Close"))

#load an additional library
library(dplyr)

#Create an xts of all assets' prices
AssetPrices <- cbind.xts(Cl(SP500),
                         Cl(EAFE),
                         Cl(US10YR),
                         Cl(GSCI),
                         Cl(NAREIT),
                         Cl(TBILLYIELDS))

AssetPrices <- AssetPrices["1972-01-31::1981-09-30"]

#Create dataframe to perform calculations (seems tidyverse not compatible with xts?)
TimingModelCalcs <- data.frame(date=index(AssetPrices), coredata(AssetPrices))
TimingModelCalcs  <- mutate(TimingModelCalcs,
  "SP500.SMA" =  rollmean(SP500.Close,10,fill = 0,align = "right"),
  "EAFE.SMA" =  rollmean(EAFE.Close,10,fill = 0,align = "right"),
  "US10YR.SMA" =  rollmean(US10YR.Close,10,fill = 0,align = "right"),
  "GSCI.SMA" =  rollmean(GSCI.Close,10,fill = 0,align = "right"),
  "NAREIT.SMA" =  rollmean(NAREIT.Close,10,fill = 0,align = "right"),
  "SP500.ret" =  c(0,diff(SP500.Close)/lag(SP500.Close)[-1]),
  "EAFE.ret" =  c(0,diff(EAFE.Close)/lag(EAFE.Close)[-1]),
  "US10YR.ret" =  c(0,diff(US10YR.Close)/lag(US10YR.Close)[-1]),
  "GSCI.ret" =  c(0,diff(GSCI.Close)/lag(GSCI.Close)[-1]),
  "NAREIT.ret" =  c(0,diff(NAREIT.Close)/lag(NAREIT.Close)[-1]),
  "RF.ret" =  lag((TBILLYIELDS.Close/100)/12),
  "SP500.signal" =  lag(ifelse(SP500.Close>=SP500.SMA,1,0)),
  "EAFE.signal" =  lag(ifelse(EAFE.Close>=EAFE.SMA,1,0)),
  "US10YR.signal" =  lag(ifelse(US10YR.Close>=US10YR.SMA,1,0)),
  "GSCI.signal" =  lag(ifelse(GSCI.Close>=GSCI.SMA,1,0)),
  "NAREIT.signal" = lag(ifelse(NAREIT.Close>=NAREIT.SMA,1,0)),
  "SP500.timingret" = ifelse(SP500.signal == 1,SP500.ret,RF.ret),
  "EAFE.timingret" = ifelse(EAFE.signal == 1,EAFE.ret,RF.ret),
  "US10YR.timingret" = ifelse(US10YR.signal == 1,US10YR.ret,RF.ret),
  "GSCI.timingret" = ifelse(GSCI.signal == 1,GSCI.ret,RF.ret),
  "NAREIT.timingret" = ifelse(NAREIT.signal == 1,NAREIT.ret,RF.ret),
  "GTAA.ret" = (SP500.timingret + EAFE.timingret + US10YR.timingret + GSCI.timingret + NAREIT.timingret)/5,
  "BUYANDHOLD.ret" = (SP500.ret + EAFE.ret + US10YR.ret + GSCI.ret + NAREIT.ret)/5
)

#Create xts of calculations to analyse performance
TimingModelCalcs.xts <- xts(TimingModelCalcs[,-1], order.by = TimingModelCalcs$date)
TimingModelCalcs.xts <- TimingModelCalcs.xts[SubsetPeriod]
detach(package:dplyr)
```

#### Time invested

```{r}
library(dplyr)
TimeInvestedCalcs <- transmute(TimingModelCalcs,
  "Date" = date,
  "AssetsInvested" =  SP500.signal +  EAFE.signal + US10YR.signal + GSCI.signal + NAREIT.signal
)

TimeInvestedCalcs.xts <- xts(TimeInvestedCalcs[,-1], order.by = TimeInvestedCalcs$Date)

#Tabulate and turn into data.frame
TimeInvestedStats <- as.data.frame(table(TimeInvestedCalcs.xts))
TimeInvestedStats <- transform(TimeInvestedStats,"Percentage of Months" = prop.table(Freq))
colnames(TimeInvestedStats) <- c("Number of Positions","# of Months","% of Months")
TimeInvestedStats$`% of Months` <- round(TimeInvestedStats$`% of Months`,4)*100
rownames(TimeInvestedStats) <- c("0% Invested (all cash)",
                                 "20% Invested",
                                 "40% Invested",
                                 "60% Invested",
                                 "80% Invested",
                                 "100% Invested (fully invested)")

paste("On average the investor is ", 
      round(20*sum(c(0,1,2,3,4,5) * TimeInvestedStats$`# of Months`) / sum(TimeInvestedStats$`# of Months`),2), 
      "% invested", sep ="")

TimeInvestedStats
write.table(TimeInvestedStats, "clipboard", sep="\t", col.names=NA) #copies to clipboad for word/excel
detach(package:dplyr)
```

####Performance Charts

```{r}
Returns <- cbind.xts(TimingModelCalcs.xts$BUYANDHOLD.ret,TimingModelCalcs.xts$GTAA.ret)[SubsetPeriod]
CumReturns <- 100*cumprod(1+Returns[-1,])
colnames(CumReturns) <- c("Buy & Hold","GTAA")

chart.TimeSeries(CumReturns[SubsetPeriod],
                 main = "Buy & Hold vs Timing Model, 1973-2012, log scale",
                 date.format = "%Y",
                 colorset = c(4,2),
                 ylab = "",
                 ylog = TRUE,
                 #ylim = c(80,6000),
                 legend.loc = "left",
                 major.ticks = "years",
                 minor.ticks = FALSE)

chart.TimeSeries(CumReturns[SubsetPeriod],
                 main = "Buy & Hold vs Timing Model, 1973-2012, non-log scale",
                 date.format = "%Y",
                 colorset = c(4,2),
                 ylab = "",
                 ylog = FALSE,
                 #ylim = c(80,6000),
                 legend.loc = "left",
                 major.ticks = "years",
                 minor.ticks = FALSE)

```

```{r}
Returns <- cbind.xts(TimingModelCalcs.xts$BUYANDHOLD.ret,TimingModelCalcs.xts$GTAA.ret)[SubsetPeriod]

Rf.ret <- Return.calculate(TBILLYIELDS)[-1,]
Rf.ret <- Rf.ret[SubsetPeriod]

stats <- rbind(100*Return.annualized(Returns,scale = 12), 
               100*StdDev.annualized(Returns,scale = 12), 
               SharpeRatio.annualized(Returns,Rf = Rf.ret$TBILLYIELDS.Close),
               100*maxDrawdown(Returns,invert = FALSE),
               100*c(Return.annualized(Return.calculate(Cl(CPI))[SubsetPeriod],scale = 12))
               )

colnames(stats) <- c("Buy & Hold","GTAA")
rownames(stats) <- c("Return","Volatility","Sharpe","MaxDD","Inflation CAGR")
round(stats,2)
write.table(round(stats,4), "clipboard", sep="\t", col.names=NA)
```

### Yearly Returns

```{r}
Returns <- cbind.xts(TimingModelCalcs.xts$BUYANDHOLD.ret,TimingModelCalcs.xts$GTAA.ret)[SubsetPeriod]
YearlyReturns <- cbind.xts(yearlyReturn(100*cumprod(1+TimingModelCalcs.xts$BUYANDHOLD.ret[SubsetPeriod])),
                           yearlyReturn(100*cumprod(1+TimingModelCalcs.xts$GTAA.ret[SubsetPeriod])))[-1,]

colnames(YearlyReturns) <- c("Buy & Hold","GTAA")

round(100*YearlyReturns,2)

YearlyStats <- rbind(Return.annualized(YearlyReturns)*100, 
               StdDev.annualized(YearlyReturns)*100, 
               SharpeRatio.annualized(YearlyReturns,Rf = 0.0541),
               maxDrawdown(YearlyReturns,invert = FALSE)*100,
               c(100*Return.annualized(Return.calculate(Cl(CPI))[SubsetPeriod],scale = 12))
               )

round(YearlyStats,2)
```


#### Yearly Returns since 2012
```{r}
Returns <- cbind.xts(TimingModelCalcs.xts$BUYANDHOLD.ret,TimingModelCalcs.xts$GTAA.ret)[SubsetPeriod]
YearlyReturns <- cbind.xts(yearlyReturn(100*cumprod(1+TimingModelCalcs.xts$BUYANDHOLD.ret[SubsetPeriod])),
                           yearlyReturn(100*cumprod(1+TimingModelCalcs.xts$GTAA.ret[SubsetPeriod])))[-1,]

colnames(YearlyReturns) <- c("Buy & Hold","GTAA")
round(100*YearlyReturns,2)
```



