---
title: "SA Assets"
output: html_notebook
---

To do:
SA assets
Daily drawdowns
Relative performance / rolling perofrmance / alpha
10 worst periods / 10 best periods 

```{r, message=FALSE, warning=FALSE}
#Load required packages
library(PerformanceAnalytics)
library(quantstrat)

#Set Symbols
symbols <- c("RiskFree","DomesticEquity","GlobalEquity","FixedIncome","Commodities","RealEstate","CPI")

#Import saved pricing data csv files as xts
getSymbols(symbols,
           src = "csv",
           dir="../Data/CSV files/SA/",
           col.names=c("Close"))
```

```{r}
AllAssets <- cbind.xts(Cl(RISKFREE),
                       Cl(DOMESTICEQUITY),
                       Cl(GLOBALEQUITY),
                       Cl(FIXEDINCOME),
                       Cl(COMMODITIES),
                       Cl(REALESTATE),
                       Cl(CPI))                       

AllAssets <- AllAssets["2002-12-31::2016-12-31"]
colnames(AllAssets) <- symbols

AllAssets.ret <- Return.calculate(AllAssets)[-1,]
AllAssets.cumret <- 100*cumprod(1+ ROC(AllAssets, type = "discrete")[-1,])

chart.TimeSeries(AllAssets.cumret["1972-12-31::2012-12-31"],
                 main = "Figure 3 - SA Asset Class Returns 2003-2012, Log Scale",
                 #lty = "2",
                 ylab = "",
                 ylog = TRUE,
                 ylim = c(40,6000),
                 date.format = "%Y",
                 major.ticks = "years",
                 legend.loc = "bottomright",
                 colorset = c("orangered3","olivedrab","slateblue","blue","gold2","dodgerblue2","cornflowerblue"), #bluefocus, #create own colorset at some point
                 minor.ticks =FALSE)
```
how to calculate returns with NA
