---
title: "FRED T-Bills Download"
output: html_notebook
---

This file downloads the T-Bills rate

```{r}
#clean workspace 
rm(list=ls()[! ls() %in% c("object1","object2")]) #remove all but the objects you define e.g. object1 and object2
```

```{r, message=FALSE}
#load required packages
library(RQuantLib)
library(quantstrat) 
library(quantmod)
library(PerformanceAnalytics)
library(tidyquant)
library(tidyverse)
```

```{r}
#Download FRED data for 10Yr US Bonds
start.date <- as.Date("1972-1-31")
end.date <- as.Date("2016-12-31")

getSymbols("DTB3", src="FRED") #download data

Tbill.yield <- to.monthly(DTB3,indexAt='lastof',drop.time=TRUE)[,4] #convert to monthly
Tbill.yield <- Tbill.yield[paste(start.date,end.date,sep="/")] #subset to required period

rm(start.date,end.date)
```

```{r}
#save as CSV files
write.zoo(Tbill.yield, file="CSV files/TBillYields.csv", sep=",")
```

```{r}
TRCalcs <- Tbill.yield
TRCalcs$Yield <- Tbill.yield/12/100
TRCalcs$Index <- 100

for (i in 2:NROW(TRCalcs)-1){
  TRCalcs$Index[i+1,1] <- (1+TRCalcs$Yield[i])*TRCalcs$Index[i]
}

TBillIndex <- TRCalcs[,3]
colnames(TBillIndex) <- c("TBILLS.Close")
```

To do:

* check this is right way to calculate TR index for Rf
* Can this be done better with a mutate?

```{r}
#save as CSV files
write.zoo(TBillIndex, file="CSV files/TBILLS.csv", sep=",")
```



